"""Give the apps that already exist what the new ones are born with.

Round 20 adds two things to every app: a brief (what it is for, how it is
built, what changed) and a designed icon. New builds get both at
``create_app_file`` / ``present_app``, because the model is right there and
already knows. The apps a tenant built last week get neither, and would keep
getting neither forever — an edit to one of them would read a missing brief,
and its card would keep the monogram.

So the backfill runs where every repair in this pipeline runs: **off the list
route**, once per container, in the background. That is the shape round 19
settled on for the manifest self-heal — there is no migration to write and no
fleet to sweep, because every tenant opens Files.

Two speeds, deliberately:

* **Synchronous and free** — the derived half of the brief and a fallback
  icon. String work, no model, milliseconds per app. This runs inline so the
  first list call after an upgrade already leaves every app with a structure
  map and a tile that is not broken.
* **Background and metered** — the narrative and the designed mark, one
  model call per app, strictly one at a time. This is what "generated by
  reading each app" means, and it is why it does not run inline: twenty-two
  apps is twenty-two calls, and nobody should wait for that to open a list.

Every part is best-effort. A container with no model reachable ends with
structure maps, histories and monogram tiles, all of them honest about being
provisional, and upgrades on the next boot that can reach one.
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Dict, Optional

from app.agent.skills.builtins.app_html import appskill, logo, store
from app.agent.skills.builtins.app_html.store import AppStoreError

logger = logging.getLogger(__name__)

#: Model that reads an app and writes its brief. Pinned — see
#: `vision.REVIEW_MODEL` for why `model=None` is never right here.
BRIEF_MODEL = "gpt-4o-mini"
BRIEF_TIMEOUT_S = 45

#: How much of the app the reader is shown. Head and tail, because the head
#: carries the styles and the markup (which is what the brief is about) and
#: the tail carries the end of the script. The middle of a large app is game
#: loop internals, which the structure digest already summarises.
READ_HEAD_CHARS = 14_000
READ_TAIL_CHARS = 3_000

#: Apps per background pass. A heavy library is a few dozen; the cap stops a
#: pathological volume turning one list call into an unbounded spend.
MAX_PER_PASS = 40

_SYSTEM = (
    "You are reading a single-file HTML app in order to write its internal "
    "brief — a working note kept beside the app, read by whoever edits it "
    "next, never shown to the person who owns it.\n"
    "\n"
    "Write markdown with exactly these headings and nothing before or after "
    "them:\n"
    "\n"
    "## What it is\n"
    "One paragraph: what the app does, who would use it, and what problem it "
    "was built to solve. Infer the intent from the app itself — do not "
    "hedge, do not say 'appears to' on every line, and do not describe the "
    "code.\n"
    "\n"
    "## Core flows\n"
    "The two to five things a person actually does with it, in order, as "
    "bullets. Start each with the user's action.\n"
    "\n"
    "## Features, states and controls\n"
    "Bullets. Every control and what it does; every state the app can be in "
    "(empty, playing, paused, over, saved) and what puts it there.\n"
    "\n"
    "## Design decisions\n"
    "Bullets. The palette and what it is doing, the type, the spacing, the "
    "one element that gives the app its character — and WHY each is that "
    "way, read off the choices actually made in the file.\n"
    "\n"
    "Be specific and be brief. This is a note for someone about to change "
    "the app, not a description for a catalogue."
)


def _excerpt(html: str) -> str:
    if len(html) <= READ_HEAD_CHARS + READ_TAIL_CHARS:
        return html
    omitted = len(html) - READ_HEAD_CHARS - READ_TAIL_CHARS
    return (
        f"{html[:READ_HEAD_CHARS]}\n\n[… {omitted:,} characters omitted …]\n\n"
        f"{html[-READ_TAIL_CHARS:]}"
    )


_HEADING_RE = re.compile(r"^\s*#{1,6}\s*what it is\b", re.IGNORECASE | re.MULTILINE)


async def write_narrative(
    slug: str, *, title: str, html: str, revision: int, user_id: str = "",
) -> bool:
    """Read one app and write the model-authored half of its brief.

    Returns True only if a narrative was actually stored. A model that could
    not be reached, or that answered with something that is not a brief,
    leaves the existing (derived-only) file exactly as it was — never a
    placeholder paragraph that would then read, to the next editor, as the
    app's stated purpose.
    """
    try:
        from app.services.internal_llm import call_system_llm
        raw = await asyncio.wait_for(
            call_system_llm(
                user_id=user_id or "",
                operation_type="system.app_html.brief_backfill",
                model=BRIEF_MODEL,
                max_tokens=1200,
                system=_SYSTEM,
                messages=[{"role": "user", "content": (
                    f'App name: "{title or slug}".\n\n'
                    f"Structure, derived from the file:\n"
                    f"{appskill.structure_digest(html)}\n\n"
                    f"The file:\n{_excerpt(html)}"
                )}],
                timeout=BRIEF_TIMEOUT_S,
            ),
            timeout=BRIEF_TIMEOUT_S,
        )
    except asyncio.TimeoutError:
        logger.warning("[app_html] brief backfill timed out for %s", slug)
        return False
    except Exception:  # noqa: BLE001 - a missing model must not break the list
        logger.warning("[app_html] brief backfill could not run for %s", slug,
                       exc_info=True)
        return False

    body = (raw or "").strip()
    if len(body) < appskill.MIN_NARRATIVE_CHARS or not _HEADING_RE.search(body):
        logger.warning(
            "[app_html] brief backfill for %s did not come back as a brief "
            "(%d chars) — leaving the derived brief alone", slug, len(body),
        )
        return False
    try:
        appskill.save(
            slug, title=title, html=html, revision=revision, narrative=body,
            history_line="brief written by reading the app (backfill)",
        )
    except (OSError, AppStoreError):
        logger.warning("[app_html] could not store the backfilled brief for %s",
                       slug, exc_info=True)
        return False
    return True


def purpose_line(slug: str) -> str:
    """The app's own one-line statement of what it is, for the icon prompt.

    Read from the brief rather than from the title: "Nokia Snake Classic"
    tells an icon model less than the first sentence under *What it is*.
    """
    brief = appskill.read(slug)
    if brief is None or not brief.narrative:
        return ""
    for line in brief.narrative.splitlines():
        line = line.strip().lstrip("#").strip()
        if line and not line.startswith(("##", "-", "*")) and len(line) > 30:
            return line[:400]
    return ""


async def _one(slug: str, user_id: str) -> Optional[str]:
    """Bring one app up to date. Returns what moved, or None."""
    rec = store.read_manifest().get(slug)
    if rec is None or not store.exists(slug):
        return None
    html = store.read_app(slug)
    moved = []

    brief = appskill.read(slug)
    if brief is None or not brief.has_narrative:
        if await write_narrative(
            slug, title=rec.title or slug, html=html,
            revision=rec.revision, user_id=user_id,
        ):
            moved.append("brief")

    purpose = purpose_line(slug)
    if logo.is_stale(slug, title=rec.title or slug, purpose=purpose):
        _svg, source = await logo.ensure_icon(
            slug, title=rec.title or slug, purpose=purpose, user_id=user_id,
        )
        if source == "model":
            moved.append("icon")
    return "+".join(moved) or None


#: One pass per process. The work is idempotent, so a second pass would be
#: harmless and pointless — and this route is hit on every Files open.
_started = False
_lock = asyncio.Lock()


def already_ran() -> bool:
    return _started


async def run(user_id: str = "", limit: int = MAX_PER_PASS) -> Dict[str, str]:
    """Read every app that is missing a brief or an icon and write them.

    Sequential on purpose: this is background work competing with the
    tenant's own chat for the same LLM budget and the same event loop, and
    twenty parallel calls to buy twenty icons is not a trade anyone asked
    for.
    """
    from app.agent.skills.builtins.app_html import vision
    global _started
    async with _lock:
        if _started:
            return {}
        _started = True
    out: Dict[str, str] = {}
    if not vision.can_call_model():
        # Not marked done — `_started` already is, and that is the point: this
        # pass is over, but nothing was written, so the NEXT boot (which may
        # have a credential) tries again rather than inheriting a decision
        # made on a container that could never have succeeded.
        logger.info("[app_html] backfill skipped — no model is reachable")
        return out
    try:
        slugs = list(store.read_manifest())[:limit]
    except Exception:  # noqa: BLE001
        return out
    for slug in slugs:
        try:
            moved = await _one(slug, user_id)
        except (OSError, AppStoreError):
            logger.debug("[app_html] backfill failed for %s", slug, exc_info=True)
            continue
        except Exception:  # noqa: BLE001 - one bad app must not cost the rest
            logger.warning("[app_html] backfill errored for %s", slug, exc_info=True)
            continue
        if moved:
            out[slug] = moved
    if out:
        logger.info("[app_html] backfilled %d app(s): %s", len(out), out)
    else:
        logger.info("[app_html] backfill pass found nothing to do")
    return out


def schedule(user_id: str = "") -> bool:
    """Kick the background pass, once. True if this call started it.

    Fire-and-forget with a held reference: a bare `create_task` can be
    garbage-collected mid-flight, which would leave the backfill half done
    with nothing logged.
    """
    global _background_task
    if _started or _background_task is not None:
        return False
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        return False
    _background_task = loop.create_task(run(user_id))
    _background_task.add_done_callback(_clear_task)
    return True


_background_task: Optional[asyncio.Task] = None


def _clear_task(task: "asyncio.Task") -> None:
    global _background_task
    _background_task = None
    if task.cancelled():
        return
    exc = task.exception()
    if exc is not None:
        logger.warning("[app_html] backfill task failed: %s", exc)
